#
# Marlin Firmware
# PlatformIO Configuration File
#

#################################
#
# STM32F2 Architecture with unified STM32 HAL
#
# Naming Example: STM32F207ZCT6
#
#   F : Foundation (sometimes High Performance F2/F4)
#   2 : Cortex M3 core (0:M0, 1-2:M3, 3-4:M4, 7:M7)
#  07 : Line/Features
#   Z : 144 pins  (T:36, C:48, R: 64 or 66, V:100, I:176)
#   C : 256KB Flash-memory  (B: 128KB, D:384KB, E:512KB, G:1024KB)
#   T : LQFP package
#   6 : -40...85°C   (6: ...85°C 7: ...105°C)
#
#################################

#
# Zortrax Inventure (STM32F207ZCT6)
#
[env:STM32F207ZC_zortrax_inventure]
extends                     = stm32_variant
board                       = nucleo_f207zg
build_flags                 = ${stm32_variant.build_flags} -DDEBUG_LEVEL=0
monitor_speed               = 115200
board_build.mcu             = stm32f207zct6
board_build.offset          = 0x10000
board_upload.offset_address = 0x08010000
